"""Configuration package for the timeline reporter project.

This package provides centralized configuration including:
- API keys and credentials
- Model settings and parameters
- Database configuration
- All prompts used across the pipeline
"""

# Import all settings, prompts, curation, discovery, research, deduplication and cloudflare
# configuration
from .cloudflare_config import (
    AUDIO_CONTENT_TYPE_MAP,
    AUDIO_FILE_METADATA,
    CDN_CACHE_CONTROL,
    CDN_ENABLE_COMPRESSION,
    CLOUDFLARE_R2_CUSTOM_DOMAIN,
    DEFAULT_AUDIO_CONTENT_TYPE,
    R2_CDN_URL_TEMPLATE,
    R2_ENDPOINT_URL_TEMPLATE,
    R2_REGION,
    R2_SIGNATURE_VERSION,
    STORAGE_PATH_PREFIX,
)
from .curation_config import (
    CRITERIA_EVALUATION_PROMPT_TEMPLATE,
    CRITERIA_WEIGHTS,
    # Curation Configuration
    CURATION_MODEL,
    MAX_LEADS,
    MIN_GROUP_SIZE_FOR_PAIRWISE,
    MIN_LEADS,
    MIN_WEIGHTED_SCORE,
    PAIRWISE_COMPARISON_PROMPT_TEMPLATE,
    PAIRWISE_SCORE_WEIGHT,
    SCORE_SIMILARITY,
    WEIGHTED_SCORE_WEIGHT,
)
from .deduplication_config import (
    # Deduplication Configuration
    EMBEDDING_DIMENSIONS,
    EMBEDDING_MODEL,
    INCLUDE_METADATA,
    METRIC,
    REQUIRED_METADATA_FIELDS,
    SIMILARITY_THRESHOLD,
    TOP_K_RESULTS,
    VECTOR_ID_PREFIX,
    # Deduplication Prompts
    DEDUPLICATION_SYSTEM_PROMPT,
    DEDUPLICATION_PROMPT_TEMPLATE,
    # Deduplication Model Configuration
    DEDUPLICATION_MODEL,
    LOOKBACK_HOURS,
)
from .discovery_config import (
    DISCOVERY_CATEGORIES,
    DISCOVERY_CATEGORY_INSTRUCTIONS,
    DISCOVERY_ENTERTAINMENT_INSTRUCTIONS,
    DISCOVERY_ENVIRONMENT_INSTRUCTIONS,
    DISCOVERY_POLITICS_INSTRUCTIONS,
    # Discovery Prompts
    DISCOVERY_SYSTEM_PROMPT,
    # Discovery Configuration
    LEAD_DISCOVERY_MODEL,
    LEAD_DISCOVERY_JSON_SCHEMA,
    SEARCH_CONTEXT_SIZE,
    # Discovery Timeouts
    DISCOVERY_TIMEOUT_SECONDS,
)
from .research_config import (
    # Research Configuration
    LEAD_RESEARCH_MODEL,
    RESEARCH_INSTRUCTIONS,
    # Research Prompts
    RESEARCH_SYSTEM_PROMPT,
    SEARCH_CONTEXT_SIZE as RESEARCH_SEARCH_CONTEXT_SIZE,
    # Research Timeouts
    RESEARCH_TIMEOUT_SECONDS,
)
from .settings import (
    # Cloudflare R2 Configuration
    CLOUDFLARE_ACCOUNT_ID,
    CLOUDFLARE_R2_ACCESS_KEY,
    CLOUDFLARE_R2_BUCKET,
    CLOUDFLARE_R2_CUSTOM_DOMAIN,
    CLOUDFLARE_R2_SECRET_KEY,
    CLOUD_PROVIDER,
    CLOUD_REGION,
    MONGODB_COLLECTION_NAME,
    MONGODB_COLLECTION_NAME_AUDIO,
    # MongoDB Configuration
    MONGODB_DATABASE_NAME,
    MONGODB_URI,
    # API Keys
    OPENAI_API_KEY,
    PERPLEXITY_API_KEY,
    PINECONE_API_KEY,
    # Pinecone Configuration
    PINECONE_INDEX_NAME,
)


__all__ = [
    # API Keys
    "OPENAI_API_KEY",
    "PINECONE_API_KEY",
    "PERPLEXITY_API_KEY",
    "MONGODB_URI",
    # Pinecone Configuration
    "PINECONE_INDEX_NAME",
    "CLOUD_PROVIDER",
    "CLOUD_REGION",
    # MongoDB Configuration
    "MONGODB_DATABASE_NAME",
    "MONGODB_COLLECTION_NAME",
    "MONGODB_COLLECTION_NAME_AUDIO",
    # Cloudflare R2 Configuration
    "CLOUDFLARE_ACCOUNT_ID",
    "CLOUDFLARE_R2_ACCESS_KEY", 
    "CLOUDFLARE_R2_SECRET_KEY",
    "CLOUDFLARE_R2_BUCKET",
    "CLOUDFLARE_R2_CUSTOM_DOMAIN",
    "CDN_CACHE_CONTROL",
    "CDN_ENABLE_COMPRESSION",
    "STORAGE_PATH_PREFIX",
    "AUDIO_FILE_METADATA",
    "AUDIO_CONTENT_TYPE_MAP",
    "DEFAULT_AUDIO_CONTENT_TYPE",
    "R2_ENDPOINT_URL_TEMPLATE",
    "R2_CDN_URL_TEMPLATE",
    "R2_SIGNATURE_VERSION",
    "R2_REGION",
    # Discovery Configuration
    "LEAD_DISCOVERY_MODEL",
    "LEAD_DISCOVERY_JSON_SCHEMA",
    "SEARCH_CONTEXT_SIZE",
    "DISCOVERY_CATEGORIES",
    "DISCOVERY_CATEGORY_INSTRUCTIONS",
    "DISCOVERY_TIMEOUT_SECONDS",
    # Curation Configuration
    "CURATION_MODEL",
    "MIN_WEIGHTED_SCORE",
    "MAX_LEADS",
    "MIN_LEADS",
    "SCORE_SIMILARITY",
    "CRITERIA_WEIGHTS",
    "MIN_GROUP_SIZE_FOR_PAIRWISE",
    "WEIGHTED_SCORE_WEIGHT",
    "PAIRWISE_SCORE_WEIGHT",
    # Research Configuration
    "LEAD_RESEARCH_MODEL",
    "RESEARCH_SEARCH_CONTEXT_SIZE",
    "RESEARCH_TIMEOUT_SECONDS",

    # Deduplication Configuration
    "SIMILARITY_THRESHOLD",
    "TOP_K_RESULTS",
    "EMBEDDING_MODEL",
    "EMBEDDING_DIMENSIONS",
    "METRIC",
    "VECTOR_ID_PREFIX",
    "INCLUDE_METADATA",
    "REQUIRED_METADATA_FIELDS",
    "DEDUPLICATION_MODEL",
    "LOOKBACK_HOURS",
    # Deduplication Prompts
    "DEDUPLICATION_SYSTEM_PROMPT",
    "DEDUPLICATION_PROMPT_TEMPLATE",
    # Discovery Prompts
    "DISCOVERY_SYSTEM_PROMPT",
    "DISCOVERY_POLITICS_INSTRUCTIONS",
    "DISCOVERY_ENVIRONMENT_INSTRUCTIONS",
    "DISCOVERY_ENTERTAINMENT_INSTRUCTIONS",
    # Decision/Curation Prompts
    "CRITERIA_EVALUATION_PROMPT_TEMPLATE",
    "PAIRWISE_COMPARISON_PROMPT_TEMPLATE",
    # Research Prompts
    "RESEARCH_SYSTEM_PROMPT",
    "RESEARCH_INSTRUCTIONS",

]
